[bar.widgets]
border_width = 0.5
end = [
    "ram",
    "cpu",
    "temp",
    "keyboard_layout",
    "network",
    "bluetooth",
    "volume",
    "input_volume",
    "brightness",
    "battery",
    "bluetooth",
    "notifications"
]
font_family = "JetBrainsMono Nerd Font"
margin_edge = 0
margin_ends = 0
padding = 1
panel_overlap = 0
position = "bottom"
radius = 0
shadow = false
show_on_workspace_switch = false
start = [ "workspaces", "clock", "date" ]
thickness = 20
widget_spacing = 10

[battery]
warning_threshold = 30

[calendar]
enabled = true

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "mic_mute"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[keybinds]
left = [ "Left" ]
validate = [ "Return", "space" ]

[location]
address = "Rennes, France"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 768.0
    cy = 745.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true
temperature_day = 6000

[shell]
avatar_path = "/home/nezutero/pics/pfps/1024x1024-0f70297b3641fe1a62a71762ee243c3b.jpg"
clipboard_history_max_entries = 1000
ui_scale = 1.2500000111758709

    [shell.launcher]
    categories = false
    session_search = true
    show_icons = false

    [shell.panel]
    floating_offset = 0
    transparency_mode = "soft"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [[shell.session.actions]]
    action = "command"
    command = "notify-send 'Noctalia' 'Custom session entry'"
    countdown_seconds = 0.0
    enabled = false
    variant = "default"

[theme]
community_palette = "Kanagawa Dragon"
source = "community"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "kitty", "qt" ]
    community_ids = [ "zen-browser", "neovim", "fuzzel", "rofi", "telegram", "yazi", "zathura" ]

[wallpaper]
directory = "/home/nezutero/walls"

    [wallpaper.default]
    path = "/home/nezutero/walls/peacefulness.png"

    [wallpaper.last]
    path = "/home/nezutero/walls/peacefulness.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/nezutero/walls/peacefulness.png"

[widget.clock]
format = "{:%H:%M:%S} ::"

[widget.date]
format = "%a %d, %b :: (%d/%m/%y)"

[widget.spacer_2]
type = "spacer"

[widget.workspaces]
active_pill_size = 1.1499999999999999
capsule_radius = 5
empty_color = "primary"
focused_color = "#AF9A1F"
font_weight = 700
hide_when_empty = true
inactive_pill_size = 1.1499999999999999
occupied_color = "primary"
scale = 1.1000000000000001